// dsh-bilingual-ui — browser half (generated by scripts/build.mjs; edit src/*.mjs)
window.__ModuleLoader__.load({
	id: "dsh-bilingual-ui",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
/**
 * dsh-bilingual-ui — generic bilingual ("中文 English") label engine.
 *
 * Third-party plugins register their UI copy in English; the shell just
 * renders it. This engine rewrites those labels at runtime, Chinese first with
 * the English right behind it ("联网搜索 Search"), on the surfaces where
 * plugin labels are actually printed:
 *
 *  1. the slash-command popup (`/`), whose core label dictionary only covers
 *     DSH's own commands — a plugin command shows its raw English `name`;
 *  2. tab strips — the chat panel's tabs and Settings → Built-in plugins tabs;
 *  3. the Plugins page — the manager prints `shortName(pkg.name)`.
 *
 * Resolution is three-tier so NEW plugins work without editing this file:
 *
 *  tier 1  PLUGIN_TITLES / COMMAND_LABELS / TAB_LABELS — curated exact labels
 *          (better phrasing than a machine composition, e.g. 提示词增强).
 *  tier 2  GLOSSARY — word-by-word composition of unknown labels
 *          ("context-status" → 上下文状态, "My Plugins" → 我的插件). A label is
 *          only wrapped when EVERY word is known, so nothing half-translated
 *          ever reaches the screen.
 *  tier 3  leave it alone (English) — the safe default.
 *
 * Three hard rules keep the engine from fighting the ecosystem:
 *
 *  - DSH core's own copy is never wrapped (CORE_LABELS).
 *  - Labels that are already Chinese (阅读) are never touched — the engine only
 *    wraps labels that are pure English.
 *  - The Settings LEFT NAV is never touched: its rows are located by exact
 *    label text by several plugins — dsh-settings-plugin-hub aligns its ledger
 *    to the nav by label (hide / pin / open-by-id all depend on it), and
 *    dsh-better-display / dsh-context-compactor / dsh-archived-chats pin their
 *    nav icons by matching their own label. Rewriting a nav label silently
 *    breaks those plugins, so the nav keeps each plugin's own copy.
 *
 * The rewrite is a runtime DOM edit (no core patching, no other plugin's
 * source touched), idempotent and self-healing: every pass compares the
 * rendered text with the target, so a shell re-render that restores the
 * original label is simply rewritten again. A DSH or plugin update therefore
 * cannot lose the change — worst case the DOM shape moves and the labels fall
 * back to the plugin's own text.
 *
 * @module
 */

/** Curated command-popup labels (tier 1), keyed by the command name shown. */
const COMMAND_LABELS = {
  // this plugin's own neighbour, kept verbatim: the user's reference wording
  search: "联网搜索 Search",
  // dsh-context-compactor
  "context-status": "上下文状态 Context Status",
  "enhance-prompt": "提示词增强 Enhance Prompt",
  reflect: "每日反思 Reflect",
  truncations: "截断记录 Truncations",
  // mnemon
  mnemon: "外置记忆 Mnemon",
  // ThoughtDAG
  why: "历史检索 Why",
};

/** Curated tab labels (tier 1), keyed by the currently rendered text. */
const TAB_LABELS = {
  "Context": "上下文 Context", // dsh-context
  "Memory System": "记忆系统 Memory System", // mnemon
  "Plugin configuration": "插件配置 Plugin Configuration", // dsh-plugin-config-compat
  "My Plugins": "我的插件 My Plugins", // dsh-my-plugins
};

/**
 * Curated Plugins-page titles (tier 1), keyed by the package short name
 * exactly as the manager computes it. Anything absent falls through to the
 * glossary, so a newly installed plugin still gets a bilingual card.
 */
const PLUGIN_TITLES = {
  "archived-chats": "归档会话 Archived Chats",
  "better-display": "交互阅读 Better Display",
  "context": "上下文洞察 Context",
  "context-compactor": "上下文压缩 Context Compactor",
  "cool-theme": "主题美化 Cool Theme",
  "cost-meter": "费用统计 Cost Meter",
  dshmarket: "插件市场 Plugin Market",
  "hindsight-coding-agents": "长期记忆 Hindsight Coding Agents",
  mnemon: "记忆系统 Mnemon",
  "my-plugins": "我的插件 My Plugins",
  omnisearch: "全网搜索 Omnisearch",
  "plugin-capabilities": "技能与 MCP Plugin Capabilities",
  "plugin-config-compat": "插件配置兼容 Plugin Config Compat",
  "plugin-mobile-gateway": "移动网关 Plugin Mobile Gateway",
  "settings-mobile-nav": "设置移动端导航 Settings Mobile Nav",
  "settings-plugin-hub": "第三方插件收纳 Settings Plugin Hub",
  thoughtdag: "思维图谱 ThoughtDAG",
  "univer-office": "在线文档 Univer Office",
  "vision-assistant": "视觉助手 Vision Assistant",
  "bilingual-ui": "界面双语 Bilingual UI", // this plugin
};

/** Word → Chinese glossary (tier 2). Composition joins the Chinese halves. */
const GLOSSARY = {
  // search & fetch
  search: "搜索", web: "网页", fetch: "抓取", engine: "引擎", provider: "提供方",
  source: "来源", platform: "平台", omni: "全网", query: "查询", result: "结果",
  // context & compaction
  context: "上下文", compact: "压缩", compactor: "压缩", summary: "总结",
  enhance: "增强", prompt: "提示词", reflect: "反思", reflection: "反思",
  truncation: "截断", truncations: "截断", status: "状态", memory: "记忆",
  checkpoint: "检查点", insight: "洞察", token: "令牌", history: "历史", why: "历史",
  // plugins & settings
  plugin: "插件", plugins: "插件", settings: "设置", setting: "设置", config: "配置",
  configuration: "配置", compat: "兼容", compatibility: "兼容", option: "选项",
  options: "选项", manager: "管理", hub: "收纳",
  // ui surfaces
  panel: "面板", page: "页面", view: "视图", list: "列表", card: "卡片", tab: "标签页",
  nav: "导航", navigation: "导航", menu: "菜单", button: "按钮", dialog: "弹窗",
  overlay: "浮层", display: "显示", reader: "阅读", reading: "阅读", system: "系统",
  // infra
  mobile: "移动", gateway: "网关", server: "服务器", client: "客户端", host: "宿主",
  proxy: "代理", network: "网络", connection: "连接", bridge: "桥接",
  // models & cost
  model: "模型", vision: "视觉", assistant: "助手", multimodal: "多模态", ocr: "文字识别", image: "图片",
  cost: "费用", meter: "计量", billing: "计费", price: "价格", pricing: "定价",
  quota: "额度", usage: "用量", peak: "峰", budget: "预算", balance: "余额",
  // themes, market, docs
  theme: "主题", market: "市场", document: "文档", office: "办公", thought: "思维",
  dag: "图谱", graph: "图谱", archive: "归档", archives: "归档", archived: "归档",
  chat: "聊天", session: "会话", mnemon: "记忆", better: "更好", cool: "酷",
  // tools & agents
  tool: "工具", tools: "工具", skill: "技能", skills: "技能", capability: "能力",
  capabilities: "能力", task: "任务", agent: "代理", team: "团队", board: "看板",
  preset: "预设", loop: "循环", shell: "命令行", experimental: "实验性", profile: "配置档",
  // verbs & adjectives
  check: "检查", sync: "同步", update: "更新", install: "安装", uninstall: "卸载",
  enable: "启用", disable: "停用", import: "导入", export: "导出", backup: "备份",
  restore: "恢复", delete: "删除", remove: "移除", add: "添加", edit: "编辑",
  save: "保存", open: "打开", close: "关闭", refresh: "刷新", retry: "重试",
  advanced: "高级", free: "免费", key: "密钥", keyless: "免密钥", my: "我的",
  all: "全部", new: "新建", quick: "快速", auto: "自动", smart: "智能",
};

/**
 * Labels DSH core owns and localizes itself. Compared case-insensitively;
 * never wrapped on any surface.
 */
const CORE_LABELS = new Set([
  "goal", "plan", "feedback", "permission", "model", "export", "compact", "file",
  "chat", "trajectory", "plugin list", "general", "models", "built-in plugins",
  "agent presets", "archived sessions", "add", "commands", "skills", "settings",
  "plugins", "refresh", "add plugin", "official", "installed",
]);

/** Popup groups whose rows are core or non-plugin content — never wrapped. */
const SKIP_GROUPS = new Set(["Add", "Skills"]);

/** The popup's command group header — the signal that a listbox is the command popup. */
const COMMAND_GROUP = "Commands";

/** Official bundles the manager localizes itself; never wrapped. */
const OFFICIAL_SCOPE = "@deepseek-ai/";

/**
 * The plugin manager's own name compaction, mirrored so rows can be looked up
 * by the short name it prints. Keep in sync with `dsh-client-ui-plugin-manager`.
 * @param name - full package name (`@scope/pkg` or `pkg`).
 * @returns the unscoped name without the `dsh-` prefixes.
 */
function shortPluginName(name) {
  return (name.startsWith("@") ? name.slice(name.indexOf("/") + 1) : name).replace(/^dsh-(?:host-|client-)?/, "");
}

/**
 * Whether a label is pure English and therefore a wrapping candidate.
 * Chinese labels, paths, versions and non-text are rejected.
 * @param text - candidate label text.
 * @returns true when the label looks like English-only UI copy.
 */
function isEnglishOnly(text) {
  if (typeof text !== "string") return false;
  const value = text.trim();
  if (value === "" || value.length > 60) return false;
  if (/[\u2e80-\u9fff\u3040-\u30ff\uac00-\ud7af]/.test(value)) return false; // any CJK
  if (!/[A-Za-z]/.test(value)) return false;
  if (/[/\\.]/.test(value)) return false; // path / file / version-like
  return true;
}

/**
 * Split a label into glossary words: separators plus camelCase boundaries.
 * @param text - English label.
 * @returns lowercase-able word list, in order.
 */
function wordsOf(text) {
  return text
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[\s\-_]+/)
    .filter((word) => word !== "");
}

/**
 * Compose "中文 English" from the glossary. All-or-nothing: one unknown word
 * and the label is left in English rather than half-translated.
 * @param text - English-only label.
 * @returns the bilingual label, or null when it cannot be composed.
 */
function composeBilingual(text) {
  if (!isEnglishOnly(text)) return null;
  const words = wordsOf(text);
  if (words.length === 0 || words.length > 5) return null;
  const chinese = [];
  for (const word of words) {
    const hit = GLOSSARY[word.toLowerCase()];
    if (hit === undefined) return null;
    chinese.push(hit);
  }
  return `${chinese.join("")} ${text.trim()}`;
}

/**
 * Resolve one label: core copy is skipped, the curated table wins, otherwise
 * the glossary composes it.
 * @param text - currently rendered label.
 * @param overrides - tier-1 table for this surface.
 * @param options - `{ commandShape: true }` restricts to command-name shapes
 *   (letters/digits/dash/underscore only), which keeps the file/session
 *   mention popups out even though they share the listbox role.
 * @returns the bilingual label, or null to leave the text alone.
 */
function bilingualFor(text, overrides = {}, options = {}) {
  if (!isEnglishOnly(text)) return null;
  const value = text.trim();
  if (CORE_LABELS.has(value.toLowerCase())) return null;
  const hit = overrides[value] ?? overrides[value.toLowerCase()];
  if (hit !== undefined) return hit;
  if (options.commandShape === true && !/^[A-Za-z][A-Za-z0-9_-]*$/.test(value)) return null;
  return composeBilingual(value);
}

/**
 * A Plugins-page card title for one package: curated, else glossary, else null
 * (official bundles and uncomposable names stay as the manager prints them).
 * @param name - full package name.
 * @returns the bilingual title, or null.
 */
function pluginTitle(name) {
  if (typeof name !== "string" || name.startsWith(OFFICIAL_SCOPE)) return null;
  const short = shortPluginName(name);
  const hit = PLUGIN_TITLES[short] ?? PLUGIN_TITLES[short.toLowerCase()];
  if (hit !== undefined) return hit;
  return isEnglishOnly(short) ? composeBilingual(short) : null;
}

/**
 * The first descendant ELEMENT that carries non-empty text — the popup option's
 * label cell, which sits next to its description cell.
 */
function firstTextLeaf(root) {
  for (const node of Array.from(root.querySelectorAll("*"))) {
    if (node.children.length > 0) continue;
    if ((node.textContent ?? "").trim() !== "") return node;
  }
  return null;
}

/**
 * The element that owns a label: the first descendant element carrying
 * non-empty text, or the element itself when the label is its own direct text
 * node (which is how the chat tabs render it).
 */
function labelSlot(root) {
  return firstTextLeaf(root) ?? root;
}

/** Replace an element's own label text, keeping its icons and children. */
function setLabelText(el, text) {
  const textNodes = [];
  for (const node of Array.from(el.childNodes)) {
    if (node.nodeType === 3) textNodes.push(node);
  }
  if (textNodes.length > 0) {
    textNodes[0].textContent = text;
    for (const node of textNodes.slice(1)) node.textContent = "";
    return;
  }
  const leaves = Array.from(el.children).filter((child) => child.children.length === 0);
  const leaf = leaves[leaves.length - 1];
  if (leaf !== undefined) leaf.textContent = text;
}

/**
 * Wrap command labels in one open command popup. The listbox is only touched
 * when it really is the command popup: it must carry the "Commands" group
 * header, which the file/session mention popups do not.
 */
function pinCommandPopup(listbox) {
  const children = Array.from(listbox.children);
  const isCommandPopup = children.some(
    (child) => child.getAttribute?.("role") !== "option" && (child.textContent ?? "").trim() === COMMAND_GROUP,
  );
  if (!isCommandPopup) return;
  let group = "";
  for (const child of children) {
    if (child.getAttribute?.("role") === "option") {
      if (SKIP_GROUPS.has(group)) continue;
      const label = firstTextLeaf(child);
      if (label === null) continue;
      const text = (label.textContent ?? "").trim();
      const next = bilingualFor(text, COMMAND_LABELS, { commandShape: true });
      if (next !== null && text !== next) setLabelText(label, next);
      continue;
    }
    group = (child.textContent ?? "").trim();
  }
}

/** Wrap tab labels (chat panel tabs + settings page tabs). */
function pinTabs() {
  for (const tab of Array.from(document.querySelectorAll('[role="tab"]'))) {
    const slot = labelSlot(tab);
    const text = (slot.textContent ?? "").trim();
    const next = bilingualFor(text, TAB_LABELS);
    if (next !== null && text !== next) setLabelText(slot, next);
  }
}

/** Wrap Plugins-page card titles, in the list and in the opened detail view. */
function pinPluginCards() {
  for (const row of Array.from(document.querySelectorAll("li[data-plugin-package]"))) {
    const title = pluginTitle(row.getAttribute("data-plugin-package"));
    if (title === null) continue;
    const button = row.querySelector('button[class*="cardTitle"]');
    if (button === null) continue;
    const slot = labelSlot(button);
    if ((slot.textContent ?? "").trim() !== title) setLabelText(slot, title);
  }
  for (const detail of Array.from(document.querySelectorAll("[data-plugin-detail]"))) {
    const title = pluginTitle(detail.getAttribute("data-plugin-detail"));
    if (title === null) continue;
    const heading = detail.querySelector('h3[class*="detailTitle"]');
    if (heading === null) continue;
    const slot = labelSlot(heading);
    if ((slot.textContent ?? "").trim() !== title) setLabelText(slot, title);
  }
}

/**
 * Pin bilingual labels onto every plugin surface, and keep them pinned: one
 * MutationObserver re-applies after any shell re-render. Idempotent — each
 * pass compares the rendered text with its target before writing.
 */
function pinBilingualLabels() {
  if (typeof document === "undefined" || typeof MutationObserver === "undefined") return;
  const apply = () => {
    for (const listbox of Array.from(document.querySelectorAll('[role="listbox"]'))) pinCommandPopup(listbox);
    pinTabs();
    pinPluginCards();
  };
  apply();
  new MutationObserver(apply).observe(document.body, { childList: true, subtree: true });
}

/**
 * dsh-bilingual-ui — browser plugin face.
 *
 * No services are needed: the engine watches the DOM itself, so `inject` is
 * empty and `apply` just starts the observer. The label rewriting never talks
 * to the Host, touches no credentials, and patches no core bundle.
 */

/** Nothing to inject — this plugin is pure runtime DOM work. */
const inject = [];

/** Start pinning bilingual labels for the lifetime of the page. */
function apply() {
  pinBilingualLabels();
}

		exports.apply = apply;
		exports.inject = inject;
		return module.exports;
	}
});
