/**
 * dsh-bilingual-ui — build the browser bundle.
 *
 * The client-modules loader fetches `<pkg>/client.js` and expects a
 * `window.__ModuleLoader__.load({ id, factory })` registration (the same shape
 * the official bundles emit). The engine lives in `src/*.mjs` as plain ESM so
 * `node --test` can import it directly; this script strips the `export`
 * keywords and wraps both files into that factory form — no bundler, no
 * dependencies, and `lib/client.js` is always regenerated from source.
 *
 * @module
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const ID = "dsh-bilingual-ui";

/** Strip ESM export keywords so the sources can run inside the CJS-ish factory. */
function stripExports(source) {
  return source
    .replace(/^export\s+const\s+/gm, "const ")
    .replace(/^export\s+function\s+/gm, "function ")
    .replace(/^export\s+\{[^}]*\}\s*$/gm, "");
}

const engine = stripExports(readFileSync(join(root, "src/bilingual.mjs"), "utf8"));
const entry = stripExports(readFileSync(join(root, "src/client-entry.mjs"), "utf8"));

const bundle = `// dsh-bilingual-ui — browser half (generated by scripts/build.mjs; edit src/*.mjs)
window.__ModuleLoader__.load({
\tid: "${ID}",
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
${engine}
${entry}
\t\texports.apply = apply;
\t\texports.inject = inject;
\t\treturn module.exports;
\t}
});
`;

mkdirSync(join(root, "lib"), { recursive: true });
writeFileSync(join(root, "lib/client.js"), bundle);
process.stdout.write(`built lib/client.js (${bundle.length} bytes)\n`);
